version: "3.5"
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - "/app/node_modules"
      - "./:/app"
