export { Login } from './Login'
export { Word } from './Word'
export { Home } from './Home'
export { SignUpLanguage } from './SignUpLanguage'
export { EthnicityLanguage } from './SignUpLanguage/ethnicityLanguage'
