export { ContentLanguageService } from './contentLanguageService'
export { ContentLocationService } from './contentLocationService'
export { ContentTrunkService } from './contentTrunkService'
export { ContentEthnicityService } from './contentEthnicityService'
export { ContentIdiomaService } from './contentIdiomaService'
export { ContentDialetoService } from './contentDialetoService'
