name: Frontend CI

on: [pull_request]

jobs:
  Build-for-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install deps
        run: yarn install
      - name: run lint
        run: yarn lint